name: Run clang-format Linter

on: [ push ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: '.'
          extensions: 'cpp,hpp'
          clangFormatVersion: 14